### ISSUE TITLE
Fix user profile.

### ISSUE THREAD

**Issue by Eugene1992** [ncadvanced/ncadvanced#102]
- correctly place the buttons, delete unused
- add password inputs validation, they should be the same
- make profile adaptive

![cwwr5iamns](https://cloud.githubusercontent.com/assets/11740952/24019201/caae0ed6-0a9f-11e7-8270-5a89b1098c9d.gif)

**Comment by PeterJames12** [comment]
@Eugene1992  На development зарез не так, я робив пуш о 21й

**Comment by Eugene1992** [comment]
@PeterJames12 Чудно, но в это время мы видели то, что вошло в деплой 4-ого релиза.
