### ISSUE TITLE
Add tasks statistic chart to user profile.

### ISSUE THREAD

**Issue by Eugene1992** [ncadvanced/ncadvanced#106]
**Something like that.. Or more charts and info.**

![image](https://cloud.githubusercontent.com/assets/11740952/24062055/9dd0758e-0b62-11e7-8d61-a456fb0e6864.png)

**Comment by PeterJames12** [comment]
@Eugene1992 це я розумію замість цього чи окремо зробити, бо тут немає можливості зробити update
<img width="1280" alt="screen shot 2017-03-18 at 23 12 31" src="https://cloud.githubusercontent.com/assets/14931091/24076031/6a195818-0c30-11e7-8e90-d492f97705e7.png">
