### ISSUE TITLE
Implement Dao layer with new db configuration.

### ISSUE THREAD

**Issue by aveOwl** [ncadvanced/ncadvanced#32]

**Comment by vasylenko0503** [comment]
В связи с последним обсуждением 26.02.2017 21.00-22.23 была переделана модель. Теперь мы храним объекты внутри сущностный вместо их Id. В противном случае, например, что бы заполнить таблицу всех Request. Frontend должен был сделать дополнительно 4 запроса для получения всех нужных ему сущностный и корректного отображения (например имя создателя запроса, вместо его Id). Это генерировало относительно большую нагрузку на сервер. В связи с данными изменениями нужно будет поправить DAO.

**Comment by vasylenko0503** [comment]
Новые Entity уже в этой ветке, для продолжения обновите ваш локальный репозиторий
